### PR TITLE
Use bam from umend for min-var call

### PR DESCRIPTION
**Pull request by rcurrie**
I've modified the pipeline's Makefile and fabfile to only preserve the bam output from umend and use that for min-var-call. Updated umend and docker as well (see separate pull request). This means the the bam will live under umend at the end of a treeshop run. e-t-k - note my hack to delete the locally pulled rnaseq bam - expediant for the moment to make this a smaller set of code change. Doing it 'right' means possibly breaking the Makefile or re-structuring the way backhaul works...

I've run this on the TEST sample and it works both in Makefile and Treeshop

### CODE REVIEW

**Comment by hbeale** [comment]
Sounds good to me.

**Comment by rcurrie** [comment]
@e-t-k Ok to merge? Or should I hold off till your done with your run, happy either way.

**Comment by e-t-k** [comment]
@rcurrie if you don't mind waiting until next week so i can have a chance to look at it that would be great. I'm swamped today with v6 stuff.

**Comment by rcurrie** [comment]
@e-t-k no problem, standing by.

**Pull request merged**
